databases:
  - name: int_school2_development
    databaseName: int_school2_development
    user: int_school2_development

services:
  - type: web
    name: int_school2_development
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: int_school2_development
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
